// AUTHENTICATION
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const LOGIN_ERRORS = "LOGIN_ERRORS";

// QUESTIONS
export const GET_QUESTIONS = "GET_QUESTIONS";
export const GET_QUESTIONS_ERROR = "GET_QUESTIONS_ERROR";
